#pragma once
#include <Windows.h>
#include <d2d1_3.h>
#include <d2d1_3helper.h>
#include <d2d1effects_2.h>
#include <d2d1effectauthor_1.h>
#include <d2d1effecthelpers.h>
#include <d3d11_3.h>
#include <dwrite_3.h>
#include <wincodec.h>
#include <initguid.h>